### ISSUE TITLE
Capital of Kiribati

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#166]
Wikipedia says that the capital of Kiribati is Tarawa (comprising North Tarawa and South Tarawa), and this deck says it is South Tarawa. Is it an error or there is a reason for that?

**Comment by aplaice** [comment]
Thanks for bringing this up! I think you're right that this should be changed.

The reason why AUG says it's South Tarawa, is that Wikipedia used to give the capital as "South Tarawa", in the infobox, [until 2015](https://en.wikipedia.org/w/index.php?title=Kiribati&type=revision&diff=650372126&oldid=649678202), and AUG is at least that old. (In the leading text, the Wikipedia article *still* mentions the capital as South Tarawa... It also doesn't help that the current articles for both [South Tarawa](https://en.wikipedia.org/wiki/South_Tarawa) and [Tarawa](https://en.wikipedia.org/wiki/Tarawa) claim that their respective subjects are the capital of Kiribati.)

The reason for the disagreement in what the capital is, is that apparently most of the governmental offices are located in South Tarawa.

However, given that our policy here generally is to follow Wikipedia's infobox, where applicable, and given that [Kiribati's governmental (?) website agrees](http://www.kiribatitourism.gov.ki/kiribati-pacific-ocean-location/), it would make sense to change the capital to just Tarawa, possibly with some capital info to the effect of most of the offices being on South Tarawa.

The German and French Wikipedia articles list the capital as "South Tarawa" and "Tarawa-Sud" respectively, so these language versions of the deck should probably still keep/use "South Tarawa" (and its French equivalent) as the capital, though.

**Comment by josealberto4444** [comment]
Thanks for all the clarifications!

> The German and French Wikipedia articles list the capital as "South Tarawa" and "Tarawa-Sud" respectively, so these language versions of the deck should probably still keep/use "South Tarawa" (and its French equivalent) as the capital, though.

I disagree. I think it should be changed in Wikipedia, indeed, so I just changed it and added the references.

**Comment by aplaice** [comment]
> I think it should be changed in Wikipedia

On second thought, you're right.

Some French-language sources that agree with you:

https://www.diplomatie.gouv.fr/fr/dossiers-pays/kiribati/presentation-de-kiribati/

https://publications.europa.eu/code/fr/fr-5000500.htm

I've adjusted the French article to point to these, as well. (Also, some of
the copied references in the French article hadn't quite worked, as in the
English article they pointed at existing citations ("CIA" and "r1"), via
`<ref name=CIA/>` and `<ref name=r1/>`, but these weren't defined in the
French article.)

**Comment by josealberto4444** [comment]
I have absolutely no idea about German, so I did the change with the help of a friend. I only added the English references from the English article, but if you can put more, that'd be awesome. In any case, I think the most important reference is the English one written by the government. Maybe the others are outdated? I don't know.

**Comment by mighty-cthulhu** [comment]
According to the state.gov it's South Tarawa as far as the US concerned: 

> ...in the capital, South Tarawa.

https://www.state.gov/reports/2018-country-reports-on-human-rights-practices/kiribati/

**Comment by horwitz** [comment]
> According to the state.gov it's South Tarawa as far as the US concerned:
> 
> > ...in the capital, South Tarawa.
> 
> https://www.state.gov/reports/2018-country-reports-on-human-rights-practices/kiribati/

FWIW, a Bureau of Intelligence and Research [fact sheet from March 27, 2019](https://www.state.gov/independent-states-in-the-world/), (also from `state.gov`) uses just "Tarawa" (as do a lot of other hits on `state.gov`).

**Comment by aplaice** [comment]
Should the German and French versions of the capital of Kiribati also be updated?

The changes made/suggested by josealberto4444 to the French and German versions of the article (changing the capital to just "Tarawa") haven't been reverted and there have been edits by other people in the meantime, so it's likely the changes will stay, in the long run (as I think they probably should).

Perhaps we should wait a while (a couple of weeks?) for any challenges to the changes in Wikipedia, to arise, and then update the capital for the French and German, here?

**Comment by ohare93** [comment]
Wiki says South Tarawa again... https://en.wikipedia.org/wiki/Kiribati

**Comment by horwitz** [comment]
with _four_ references in the Wikipedia text right after the capital, all saying that the capital is just "Tarawa", I suspect (or at least hope) that it'll mostly quiesce to Tarawa...

**Comment by axelboc** [comment]
Re-opening! For the nth time, Wikipedia changed the capital back to _South Tarawa_ in [April 2021](https://en.wikipedia.org/wiki/Talk:Kiribati#Capital_of_Kiribati). The difference is that the article now quotes a [governmental source](https://en.wikipedia.org/wiki/Kiribati#cite_note-1). At long last! 😄 

I should add that most other Wikipedias seem to have converged to _South Tarawa_ (except for Spanish).

**Comment by josealberto4444** [comment]
Hahaha. Perfect, then. With the new guidelines, we should follow South Tarawa as that's what the English Wikipedia says, so no problem due to the Spanish Wikipedia. Anyway, I'll change it there. ^^
