### ISSUE TITLE
Add Chinese versions

### ISSUE THREAD

**Issue by GrimPixel** [anki-geo/ultimate-geography#239]
There is actually a list of country names in Chinese.
https://polyglotclub.com/wiki/Language/Mandarin-chinese/Vocabulary/Countries-in-Chinese

I can add those lacked translations: sea names and territories that are considered not “politically outside the controlling state's integral area” according to https://en.wikipedia.org/wiki/Dependent_territory. This is not a hard work since the major part is done.

**Comment by axelboc** [comment]
Thanks for your enthusiasm, the more translations, the better! 💯 

Heads up: it's quite hard to add and maintain translations, as they're all stored within a single CSV file, `data.csv`. I've been meaning to investigate a better internationalisation solution (cf. #143), but I haven't made much progress.

That being said, if you're up for a challenge, and you're willing to keep your translations up to date in the long run, please go for it! I assume you're wanting to translate to Mandarin, not Cantonese? If so, please refer to the [Chinese version of Wikipedia](https://zh.wikipedia.org/wiki/%E6%B1%89%E8%AF%AD) for country names, capitals, and so on.

Some important things to account for:

- As explained in #243, when a country or capital has multiple names (short, long, official, spoken, etc.) we always use the title of the Wikipedia article.
- Please use the capital mentioned in the infobox of each country's Chinese Wikipedia article. If an infobox lists multiple capitals, please refer to other translations for guidance -- the country may have secondary capitals, in which case they are to be mentioned in the _Capital info_ field, or it may have more than one primary capital (_Canary Islands_, _South Africa_), in which case they are to both be listed in the _Capital field_.
- It's okay if some country names and capitals don't match with other translations. They may vary between countries for political, cultural and historical reasons. The source of truth is Wikipedia.
- The deck has been translated four times already, so if you're unsure about something, chances are we've [discussed it already](https://github.com/axelboc/anki-ultimate-geography/issues?q=is%3Aissue+is%3Aclosed). If not, don't hesitate to ask!

Good luck to you! 🎉

**Comment by aplaice** [comment]
> The deck has been translated four times already, so if you're unsure about something, chances are we've discussed it already. If not, don't hesitate to ask!

One topic that won't have been brought up, because we haven't had a multi-script language before, is which script to use. In the case of Chinese, I think it should be relatively uncontroversial that simplified characters should be chosen, as they're what's used in mainland China and (AFAIK) by the main (zh) Wikipedia instance.

**Comment by GrimPixel** [comment]
I believe that you think too highly of Wikipedia.
https://en.wikipedia.org/wiki/Wikipedia:Edit_warring
https://cn.nytimes.com/china/20131030/c30wikipedia/dual/
Wikipedia is just a reference, not the law. There are a lot of irrational editors on that site. But I agree to follow that rule.

Of course I can try Cantonese. But there are not enough references about capitals.

**Comment by GrimPixel** [comment]
Chinese Wikipedia allows Simplified and Traditional Chinese and it's actually “Mandarin” instead of “Chinese”.

**Comment by GrimPixel** [comment]
If we just follow Wikipedia's titles, is it possible to fetch them automatically? Then contributors only need to check them.

**Comment by axelboc** [comment]
> Wikipedia is just a reference, not the law.

I never said otherwise, but they have a lot more maintainers than we do! 😄 Feel free to fix errors on Wikipedia if you spot any!

I think Mandarin is a fairly obvious choice to start with. It would be good to pick a script and stick to it too.

**Comment by axelboc** [comment]
> If we just follow Wikipedia's titles, is it possible to fetch them automatically? Then contributors only need to check them.

You could probably automate it somehow, but the other fields also need translating (_Country info_, _Capital info_, __Flag similarity_, etc.)

**Comment by GrimPixel** [comment]
> > If we just follow Wikipedia's titles, is it possible to fetch them automatically? Then contributors only need to check them.
> 
> You could probably automate it somehow, but the other fields also need translating (_Country info_, _Capital info_, __Flag similarity_, etc.)

Then Google Translate is in the place.

**Comment by GrimPixel** [comment]
Fetching titles is actually available:
https://stackoverflow.com/questions/4420584/how-to-get-wikipedia-page-in-multi-languages

**Comment by ukanuk** [comment]
I've released a python library to make fetching translations from interwiki links easier, see [ukanuk/wplangtools](https://github.com/ukanuk/wplangtools).

**Comment by ohare93** [comment]
@GrimPixel Still up for making a Chinese translation? :cn: If so, it is now even easier, as the new deck manager has been pulled :+1: The source csv has now been broken into multiple separate csv files inside `src/data`. 

You can now add your translation :clap: This requires 2 steps to do it yourself:
1) Add the translation as a column in each of the source files.
2) Edit the Brain Brew recipe in `recipes/source_to_anki.yaml` to build your new column to your new language deck. Just copy pasting what the others do, and changing it to match your new columns will do :+1: 

I am happy to do the second step, if you do the first :wink: 

Better yet, if you have created the translation inside Anki itself then I can do it all in <5mins, as the new deck manager can also import _from CrowdAnki_ to our Source control. Feel free to export the deck, upload a zip of it here, and I will do magic :clap: :grin:

**Comment by axelboc** [comment]
It's been a while, so closing this issue for now. If someone wants to champion this translation work, let us know and we'll reopen!
