### ISSUE TITLE
[FR] Melekeok vs Ngerulmud as capital of Palau

### ISSUE THREAD

**Issue by MaloMn** [anki-geo/ultimate-geography#342]
After extensive researches, following the merged pull request [#323](https://github.com/axelboc/anki-ultimate-geography/pull/323), I found out that the [French Wikipedia page for Palau](https://fr.wikipedia.org/wiki/Palaos) isn't quite right:
> *French Wikipedia page translated in English*: The biggest one [island], Babeldaob, is composed of 10 states out of 16, the international airport Roman-Tmetchl **and the new capital, Melekeok,** in the state of Melekeok.

Out of the 9 main languages in which the Wikipedia page about Palau is translated, only two of them state that Melekeok is the capital. On the French page, the two sources used to define Melekeok as the capital are seven years old. However, [one of them](http://archive.wikiwix.com/cache/index2.php?url=https%3A%2F%2Fwww.cia.gov%2Flibrary%2Fpublications%2Fthe-world-factbook%2Fgeos%2Fps.html) states that Ngerulmud is the capital of Palau since 2018. The other one is [a French website](https://www.diplomatie.gouv.fr/fr/dossiers-pays/republique-des-palaos/article/presentation-de-la-republique-des-palaos), and it still says that Melekeok is the capital.

Having said that, and knowing that **even in French, Melekeok and Ngerulmud are two different places**, it seems fair to say that there has been a mistake on the French Wikipedia page. Hence, I think it would be better to set the French Capital of Palau to **Ngerulmud**, just as the other translations in the deck.

Just in case, I also sent an email to the United Stated Embassy of the Republic of Palau to make sure that Ngerulmud is indeed the capital of Palau, and not just the seat of government. If I have an answer from them, I'll modify the French Wikipedia page.

**Comment by aplaice** [comment]
Thanks for digging into this!

AFAICT Ngerulmud is a suburb of Melekeok, so I think that this might be a similar situation to Sri Lanka (Sri Jayawardenepura Kotte, the real capital, is a suburb of Colombo, and hence many people (and sometimes international institutions...) incorrectly believe that Colombo is the capital).

However, the mistake (if it is such) in French Wikipedia is quite deeply rooted — the article on [Palau](https://fr.wikipedia.org/wiki/Palaos), [Ngerulmud](https://fr.wikipedia.org/wiki/Ngerulmud) and [Melekeok](https://fr.wikipedia.org/wiki/Melekeok_(ville)) all consistently claim that Melekeok is the capital. (As does [French Wikivoyage](https://fr.wikivoyage.org/wiki/Palaos).)

The citation situation is indeed bizarre — of the three sources used to support the claim that Melekeok is the capital, one (the CIA World Factbook) states that the capital is Ngerulmud, as you write. The two others, [by the French diplomatic corps](https://www.diplomatie.gouv.fr/fr/dossiers-pays/republique-des-palaos/article/presentation-de-la-republique-des-palaos) and the [UN database](https://unterm.un.org/unterm/display/record/unhq/na/ba6d30ba-2cc9-4fd9-be1d-e03e841676cd) do however agree that Melekeok is the capital.

[Larousse](https://www.larousse.fr/encyclopedie/pays/Palaos/136823) also claims that Melekeok is the capital.

Hence I do agree that Ngerulmud is the actual capital, but the French-language situation is a bit muddied.

**Comment by MaloMn** [comment]
I'm glad to know that this is not an isolated problem :) Thanks for taking the time to check that.

I completely understand that it doesn't seem right to modify the Anki deck without the "support" of Wikipedia.

I have sent another email to the French Embassy of Manille, which is in charge of the Republic of Palau. When I get an answer to one of the two emails, I'll post it here, and will or will not modify Wikipedia depending on their answer.

**Comment by axelboc** [comment]
> I have sent another email to the Embassy of France in Manila, which is in charge of the Republic of Palau. When I get an answer to one of the two emails, I'll post it here, and will or will not modify Wikipedia depending on their answer.

Great! I was actually going to suggest contacting a French embassy rather than a US embassy, as each country may have their own "capital" interpretation.

**Comment by ohare93** [comment]
> I have sent another email to the Embassy of France in Manila, which is in charge of the Republic of Palau.

Sounds so bloody serious for a Git repo 😆 Good work, mate! Reminds me of: https://www.youtube.com/watch?v=Jbix9y8iV38

**Comment by axelboc** [comment]
As per https://github.com/anki-geo/ultimate-geography/issues/416#issuecomment-821864712, we'll now officially be following English Wikipedia for capitals, so I've gone with your initial suggestion, @MaloMn, and switched to Ngerulmud in #435.

**Comment by axelboc** [comment]
For what it's worth, I've posted on [Palau's talk page](https://fr.wikipedia.org/wiki/Discussion:Palaos#Capitale)

**Comment by MaloMn** [comment]
Thanks for doing this! 
I think you did well posting it on Wikipedia's talk page. Who knows, some embassies might stumble upon it and finally answer us :')
