### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by iHumus** [anki-geo/ultimate-geography#374]
What a great deck!
I found it when I was looking for a way for my son to learn geography.
He's learning English but his native language is Hebrew,
so I made a translation that I'll be happy to add for everyone who's interested.

**Comment by ohare93** [comment]
Translations are always welcome :clap: thanks for the effort that took :rocket: 

What format do you have the translation in? If you just edited the Anki cards, then you may have little else to do, and be the first to benefit from the new deck manager :grin:

**Comment by axelboc** [comment]
@iHumus any update on this? Otherwise, I'll close the issue in a bit.
