### ISSUE TITLE
Flag similarities between Sudan and Palestine

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#404]
The flags:

Sudan            |  Palestine
:-------------------------:|:-------------------------:
![Sudan](https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg "Sudan")  |  ![Palestine](https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg "Palestine")

The flag similarity field says:

- Sudan (green arrow, red stripe)
- Palestine (red arrow, green stripe)

So, when learning, when I saw the first of them (Palestine), I expected the Sudan flag to have red and green swapped. However, black stripe also changes position, so I find this hint a bit misleading. I'm not sure if it's just my problem, though, but I wanted to report it in case you think it should be improved.

I think a more useful hint would be this one (following Cameroon/Senegal):

- Sudan (red/white/black, green arrow)
- Palestine (black/white/green, red arrow)

**Comment by aplaice** [comment]
You're right — that would (also IMO) be far clearer (and more consistent with what we do for Cameroon/Senegal)!

(I think the current wording comes from when Palestine had multiple flag similarities, and the formulation made more sense.)

**Comment by aplaice** [comment]
Current:

```
Sudan
Palestine (red arrow, green stripe)
Palästina (roter Pfeil, grüner Streifen)
Palestina (triángulo rojo, banda verde)
Palestine (flèche rouge, bande verte)
Palestina (rød trekant, grønn stripe)
Stát Palestina (červená šipka, zelený pruh)
Палестина (красная стрелка, зеленая полоса)
Palestina (rode pijl, groene streep)
Palestina (röd triangel, grönt band)
```

Suggested:
```
Palestine (black/white/green, red arrow)
Palästina (Schwarz/Weiß/Grün, roter Pfeil)
Palestina (negro/blanco/verde, triángulo rojo)
Palestine (noir/blanc/vert, flèche rouge)
Palestina (svart/hvit/grønn, rød trekant)
Stát Palestina (černá/bílá/zelená, červená šipka)
Палестина (черный/белый/зеленый, красная стрелка)
Palestina (zwart/wit/groen, rode pijl)
Palestina (svart/vit/grön, röd triangel)
```

Current:
```
Palestine
Sudan (green arrow, red stripe)
Sudan (grüner Pfeil, roter Streifen)
Sudán (triángulo verde, banda roja)
Soudan (flèche verte, bande rouge)
Sudan (grønn trekant, rød stripe)
Súdán (zelená šipka, červený pruh)
Судан (зеленая стрелка, красная полоса)
Soedan (groene pijl, rode streep)
Sudan (grön triangel, rött band)
```

Suggested:
```
Sudan (red/white/black, green arrow)
Sudan (Rot/Weiß/Schwarz, grüner Pfeil)
Sudán (rojo/blanco/negro, triángulo verde)
Soudan (rouge/blanc/noir, flèche verte)
Sudan (rød/hvit/svart, grønn trekant)
Súdán (červená/bílá/černá, zelená šipka)
Судан (красный/белый/черный, зеленая стрелка)
Soedan (rood/wit/zwart, groene pijl)
Sudan (röd/vit/svart, grön triangel)
```

### Notes:

Czech: using feminine like for Cameroon (and like is listed as the "canonical" form on Wiktionary), despite pruh being masculine...
Russian: using masculine like for Cameroon, despite полоса being masculine
Not using ё in "черный", since that's what was done for "зеленый"
Not using а́ in кра́сный, since it's been omitted elsewhere

Dutch: using uninflected (similarly to Cameroon)

Swedish: not using neutral, despite "band" being neutral (similarly as for Cameroon or Indonesia)


<hr/>

### Other fields to be made consistent:

Senegal (grønt, gult og rødt samt grønn stjerne)
Kamerun (zelená/červená/žlutá), žlutá hvězda)

**Comment by Erim24** [comment]
The German translation looks good to me

**Comment by josealberto4444** [comment]
> ### Other fields to be made consistent:
> 
> Senegal (grønt, gult og rødt samt grønn stjerne)
> Kamerun (zelená/červená/žlutá), žlutá hvězda)

I guess this should be:
```
Senegal (grønn/gul/rød, grønn stjerne)
Kamerun (zelená/červená/žlutá, žlutá hvězda)
```
so I submitted #432 including this as well. ^^
