### ISSUE TITLE
Capital of Equatorial Guinea

### ISSUE THREAD

**Issue by wfdewith** [anki-geo/ultimate-geography#406]
The capital of Equatorial Guinea is currently Malabo, but Ciudad de la Paz is the future capital. Should that be mentioned on the card in the capital info field? [Wikipedia](https://en.wikipedia.org/wiki/Ciudad_de_la_Paz) says that the government began to move in 2017, although I'm not sure how up to date that information is.

**Comment by jamesnelmore** [comment]
I think it should be mentioned. The most analogous situation I can think of is Dodoma/Dar es Salaam in Tanzania, and that is mentioned.

**Comment by axelboc** [comment]
The infobox does list _Ciudad de la Paz_ as being `under construction`, so it can definitely be mentioned in the _Capital info_ field. What about:

```
Ciudad de la Paz, currently under construction, will become the new capital.
Ciudad de la Paz, die sich derzeit im Bau befindet, wird die neue Hauptstadt werden.
Ciudad de la Paz, actualmente en construcción, se convertirá en la nueva capital.
Ciudad de la Paz, actuellement en construction, deviendra la nouvelle capitale.
Ciudad de la Paz, som for tiden er under bygging, blir den nye hovedstaden. 
Novým hlavním městem se stane Ciudad de la Paz, které je v současné době ve výstavbě.
Сьюдад-де-ла-Пас, строящийся в настоящее время, станет новой столицей.
Ciudad de la Paz, momenteel in aanbouw, zal de nieuwe hoofdstad worden.
Ciudad de la Paz, som håller på att byggas, kommer att bli den nya huvudstaden.
```

**Comment by wfdewith** [comment]
Both the English and Dutch version seem fine to me; I can't speak for the other languages.

**Comment by horwitz** [comment]
Consider avoiding definitive language like "will become" (since it is uncertain until it happens—alternatives include "is slated to become", etc.). Perhaps something like
```Ciudad de la Paz is being built to replace Malabo as capital.```

(Almost verbatim from [Wikipedia](https://en.wikipedia.org/wiki/Ciudad_de_la_Paz).)

**Comment by axelboc** [comment]
Sounds good:

```
Ciudad de la Paz is being built to replace Malabo as capital.
Ciudad de la Paz wird gebaut, um Malabo als Hauptstadt zu ersetzen.
Se está construyendo la Ciudad de la Paz para sustituir a Malabo como capital.
Ciudad de la Paz est en cours de construction pour remplacer Malabo comme capitale.
Ciudad de la Paz bygges for å erstatte Malabo som hovedstad. 
Místo hlavního města Malabo se buduje Ciudad de la Paz.
Сьюдад-де-ла-Пас строится вместо Малабо как столицы.
Ciudad de la Paz wordt gebouwd om Malabo als hoofdstad te vervangen.
Ciudad de la Paz håller på att byggas för att ersätta Malabo som huvudstad.
```

**Comment by josealberto4444** [comment]
I'd remove "la" from the Spanish translation:
```
Se está construyendo Ciudad de la Paz para sustituir a Malabo como capital.
```
It sounds strange as "Ciudad de la Paz" is similar to "Ciudad de México", for example, and we wouldn't say "la Ciudad de México". =)

**Comment by axelboc** [comment]
Seems to be part of the name, though: https://en.wikipedia.org/wiki/Ciudad_de_la_Paz - are you sure?

**Comment by josealberto4444** [comment]
Hm… AFAIU, the current official name is just "Ciudad de la Paz" and the previous name was "Oyala", and that's why the Wikipedia article says Oyala-Ciudad de la Paz in its title (but I didn't find "La Ciudad de la Paz" in the article). If you want to keep also Oyala (I think it's also a good option, but I prefer the previous one), then it should be
```
Se está construyendo Oyala-Ciudad de la Paz para sustituir a Malabo como capital.
```
but then maybe it should also be changed in other languages (as French, where it is listed only as Oyala in the title).

**Comment by axelboc** [comment]
Sorry, I just hadn't seen the `la` in front of `Ciudad de la Paz` ... thought you were talking about the one in the middle of the name 😅 -- I'll remove the one in front, no worries 😉

**Comment by axelboc** [comment]
Since `Ciudad de la Paz` is going to be the new name of the capital, I don't think it's worth using the name `Oyala` in French and other languages.
