### ISSUE TITLE
Mentioning Tel Aviv as location many embassies to Israel

### ISSUE THREAD

**Issue by jamesnelmore** [anki-geo/ultimate-geography#408]
Because the status of Jerusalem as the Israeli capital is disputed and many countries keep their embassies in Tel Aviv as a result, it might be worth adding something to that effect in Israel's _Capital Info_ field.

**Comment by aplaice** [comment]
Given the considerable controversies around the subject, I'd strongly prefer to follow our guidelines of relying on Wikipedia's infobox, as closely as possible and to be as brief as possible — i.e. for Israel just mention that Jerusalem is "disputed"...

(I'm not sure how well overzealous supporters of either side would take "we're just following Wikipedia" as a defence, but it's better than none.)

**Comment by jamesnelmore** [comment]
I guess the question is, is there anyone who recognizes Tel Aviv as the actually capital, or is that just where they keep their embassies to stay out of the conflict? Because I don't believe the former is the case, you are right we should probably not do this.

**Comment by axelboc** [comment]
With #409, the _Capital info_ field of Israël now contains "Disputed; claimed by Palestine." I think this is sufficient and in line with our guidelines. If Wikipedia ever decides to add Tel Aviv to the infobox, then we can do so here as well.
