### ISSUE TITLE
Review capital of Palestine across languages

### ISSUE THREAD

**Issue by axelboc** [anki-geo/ultimate-geography#419]
This follows #409. As mentioned in #416, on Wikipedia, some languages have East Jerusalem as the capital, not Jerusalem, and some mention both capitals in the infobox, with various qualifiers, like _de jure_, _proclaimed_, _declared_, etc. We need to review each language and make sure we are in line with our guidelines. Some of the capital info fields may have to be changed as well.

**Comment by axelboc** [comment]
The Wikipedia articles that have East Jerusalem as the capital either don't provide a source or disagree with the source they quote, the [Palestinian Declaration of Independence](https://en.wikipedia.org/wiki/Palestinian_Declaration_of_Independence), which proclaims Jerusalem as the capital. 

Best source I could find to support East Jerusalem is quoted on [Swedish Wikipedia](https://sv.wikipedia.org/wiki/Palestina_(stat)#cite_note-School_of_Public_Policy-1):

> According to one recent study, 70 percent of Palestinians support genuine peace with Israel, provided that there is a Palestinian state with East Jerusalem as its capital.

The study in question, I think is:

> Nader Said and Jerome M. Segal, "The Status of Jerusalem in the Eyes of Palestinians," Center for International and Security Studies, University of Maryland, 1997

A 24 year-old source... The information might still be accurate, I don't know, but it's fair to say that the source is no longer relevant.

Considering all this, I think we should keep Jerusalem as the capital in every language and close this issue. Any thoughts?

**Comment by aplaice** [comment]
> Considering all this, I think we should keep Jerusalem as the capital in every language and close this issue. Any thoughts?

That probably makes sense, to avoid having too many inconsistencies between languages. It's technically a violation of the policy of following each Wikipedia for each language, but I'm having increasing doubts whether that's at all scalable with the increasing number of languages...

**Comment by axelboc** [comment]
Yeah, my thinking exactly! See https://github.com/anki-geo/ultimate-geography/issues/416#issuecomment-821864712. We've had so many issues and back-and-forth because of this policy, and I can't actually find any case where this policy introduced a factually worthwhile inconsistency...
