### ISSUE TITLE
Filtered deck with example searches yields no results

### ISSUE THREAD

**Issue by danieldunderfelt** [anki-geo/ultimate-geography#423]
I'm completely new to Anki and I want to learn the flags of the world. But when I tried to create a filtered deck with the example search query from the readme, Anki says that no cards match the search query.

This is the query:

```
card:"Flag - Country"
```

Result:

![Screenshot 2021-04-20 at 19 53 24](https://user-images.githubusercontent.com/3145668/115435018-13c94280-a212-11eb-8faa-54cabd612cce.png)

**Comment by danieldunderfelt** [comment]
Apparently I need to use `"card:Flags"` instead.

**Comment by axelboc** [comment]
I would have suggested adding `deck:"Ultimate Geography"` to the query, but glad to hear you found a solution. `Flags` refers to neither a template nor a field (should be `Flag` singular), so it's very strange. 🤷
