### ISSUE TITLE
Map of Bali is missing the small world map

### ISSUE THREAD

**Issue by x51mon** [anki-geo/ultimate-geography#425]
The map of Bali is missing the small world map which indicates the position of the map section.
It makes it easier to guess the card based on that and a bit harder to locate the card section.

**Comment by josealberto4444** [comment]
What do you think about this version? I've modified the [map of Java](https://commons.wikimedia.org/wiki/File:Java_in_its_region.svg) made by @aplaice, to make colors and divisions consistent.

![Bali_in_its_region svg](https://user-images.githubusercontent.com/13300909/132212307-a932cf0a-7502-4a12-8cab-09fb449c8754.png)
