### ISSUE TITLE
Review capital of Northern Cyprus in Swedish

### ISSUE THREAD

**Issue by axelboc** [anki-geo/ultimate-geography#437]
The Swedish deck has _Nicosia_ as the capital of _Northern Cyprus_ instead of _North Nicosia_ like the other decks. I think this is a case where the new guideline of following English Wikipedia (cf. https://github.com/anki-geo/ultimate-geography/issues/416#issuecomment-821864712) justifies switching to _North Nicosia_ in Swedish.

The problem is that Swedish Wikipedia does not have an article for _North Nicosia_; only for [Nicosia](https://sv.wikipedia.org/wiki/Nicosia), so I'm not sure what to do.

---

As a side note, there's no capital hint to help distinguish the two instances of _Nicosia_ in the Swedish deck at the moment. So if we keep _Nicosia_ we should at least add a hint.

**Comment by aplaice** [comment]
FWIW Norwegian Bokmål Wikipedia also doesn't have an article for North Nicosia (nor does SNL). "Nord-Nikosia" is mentioned in the article about [Nicosia](https://no.wikipedia.org/wiki/Nikosia) and [Northern Cyprus](https://no.wikipedia.org/wiki/Nord-Kypros).

Neither does Dutch Wikipedia have an article about North Nicosia... ("North Nicosia" as the Dutch deck now calls it, isn't mentioned anywhere in the relevant articles. "Noord-Nicosia", though, is mentioned in the article about [Nicosia](https://nl.wikipedia.org/wiki/Nicosia_(Cyprus).) (The capital listed in the article about [Northern Cyprus](https://nl.wikipedia.org/wiki/Noord-Cyprus) is Lefkoşa (an alternative name of Nicosia) and linking to the article about Nicosia.)  (Should we change "North Nicosia" to "Noord-Nicosia" in the Dutch deck?) 

Hence, for Swedish, I'd suggest that we use "Nordnicosia", which is mentioned in the article about [Cyprus's geography](https://sv.wikipedia.org/wiki/Cyperns_geografi). (Using Nicosia in Swedish, but not in Dutch isn't really consistent.)

<hr/>

Additionally, [Swedish Wikipedia lists Lefkosia as an alternative name of Nicosia](https://sv.wikipedia.org/wiki/Nicosia) ("also known as...").  (None of the other Wikipedias relevant for our current language decks seem to do this — they only state that "Lefkosía" and similar are the Greek/Turkish/etc. names.)  Should we add a "Även känd som Lefkosia" to the relevant Swedish capital info(s?)?

**Comment by axelboc** [comment]
> Hence, for Swedish, I'd suggest that we use "Nordnicosia", which is mentioned in the article about Cyprus's geography. (Using Nicosia in Swedish, but not in Dutch isn't really consistent.)

Nice, well spotted! Now that we know that the name exists, I think it makes sense to use it in the deck.

> Should we add a "Även känd som Lefkosia" to the relevant Swedish capital info(s?)?

Sure, makes sense!

---

Let's maybe double check all this with @emiham.

**Comment by emiham** [comment]
> Hence, for Swedish, I'd suggest that we use "Nordnicosia", which is mentioned in the article about Cyprus's geography. (Using Nicosia in Swedish, but not in Dutch isn't really consistent.)

I propose "Norra Nicosia". "Nordnicosia" does make more sense as a name for a city, but as far as I can tell the *only* Swedish source that calls it that is Wikipedia, and only in that one link to a page that hasn't been created yet. "Norra Nicosia" is at least mentioned in some places, although it carries the implication that it's still only one city (cf. "Northern Nicosia).

There's not much written about either of the options though, so I wouldn't be opposed to "Nordnicosia" as that would probably end up being the name if it gets more established as a city. 

> Should we add a "Även känd som Lefkosia" to the relevant Swedish capital info(s?)?

This was in my original translation before I removed all the extra capital infos. I think Swedish Wikipedia is a little more eager to include alternative names and spellings than others, and from some cursory research it doesn't seem to be commonly used in other Swedish sources, so I think it's better to stay more consistent with the other translations.
