### ISSUE TITLE
Review capital(s) of the European Union

### ISSUE THREAD

**Issue by axelboc** [anki-geo/ultimate-geography#438]
Currently, the Norwegian deck lists Brussels, Strasbourg and Luxembourg together as capitals of the EU, while the other decks give only Brussels. I was about to remove the two extra capitals in Norwegian as per https://github.com/anki-geo/ultimate-geography/issues/416#issuecomment-821864712 when I noticed that the infobox on English Wikipedia no longer mentions a capital at all! It just lists the various institutions and their locations in a section called "Institutional seats".

Should we then reconsider the decision we made in #213? The way I see it, we can either:

1. remove the capital from the _European Union_ note completely (to leave only the flag and the map); or
2. list all four "institutional seats" cities (including Frankfurt, the seat of the Central Bank).

Given that there are no qualifiers such as "executive" or "legislative" in the infobox, I feel option 2 would be messy. We'd have to least all the institutions in the _Capital info_ field... Going with option 1 would have the added benefit of removing a couple of hints.

Personally, I'd rather go with option 1, especially since I've never really seen the EU as having a capital in the first place. What do you all think?

**Comment by ohare93** [comment]
Option 1 sounds better, indeed.

**Comment by aplaice** [comment]
I think it generally makes some sense to think of the EU as having a capital, but since **1.** is closer to our guidelines and leads to significantly lower complexity, I agree that it's the better choice!
