### ISSUE TITLE
Are flags of Mexico and Italy similar?

### ISSUE THREAD

**Issue by x51mon** [anki-geo/ultimate-geography#472]
I've read through the contribution guidelines and if I used the colour calculator correctly, Mexico and Italy should qualify for flag similarity with `1C 0M 0m 2n`.

I thought I'd ask first though, before opening a pull request.

**Comment by axelboc** [comment]
I get a delta E of 29, so you're right, the difference in color for the green is negligible, although right on the limit.

However, I'd argue that the difference in ratio is not negligible and constitutes a _minor_ difference, thus giving `1C 0M 1m 1n`:

- Italy: 375 / 250 = 1.5 ratio
- Mexico: 438 / 250 = 1.752 ratio

We don't have a strict guideline on ratios, but I think the difference is significant here. Considering that the delta E is right on the limit, I'd be in favour of _not_ adding similarity information for this pair of flags.

**Comment by aplaice** [comment]
I think I agree with @axelboc. (Also, as a data-point of one, I've never confused Mexico and Italy on the Flag→Country cards.)

@x51mon sorry for shooting down your contributions! :( Please feel free to argue if you disagree with our arguments!

I'll edit the [wiki page](https://github.com/anki-geo/ultimate-geography/wiki/Flag-similarities) with these and the Haiti/Liechtenstein similarities.

**Comment by x51mon** [comment]
Oh I forgot to check the ratio actually (I mostly memorize square and rectangular only).

No problem, like I wrote in #469 I assumed a different purpose of this field. 
I guess this issue can be closed then.

I kind of like how you have such clear and detailed guidelines on this :)
