### ISSUE TITLE
Fix flag similarities for Russia

### ISSUE THREAD

**Issue by saucedrum** [anki-geo/ultimate-geography#477]
The flag similarities line for Russia added in #473 is slightly messed up leading the info to be shifted to the wrong language.

The line currently is the following:
` Russia,"Slovakia (with coat of arms),"Slowakei (mit Wappen),"Eslovaquia (con escudo)","Slovaquie (avec blason)","Slovakia (med våpenskjold)","Slovensko (s erbem)","Словакия (с гербом)","Slowakije (met wapen)","Slovakien (med vapensköld)"`

But it should be like this:
` Russia,"Slovakia (with coat of arms)","Slowakei (mit Wappen)","Eslovaquia (con escudo)","Slovaquie (avec blason)","Slovakia (med våpenskjold)","Slovensko (s erbem)","Словакия (с гербом)","Slowakije (met wapen)","Slovakien (med vapensköld)"`

Note the two missing double quotes added to enclose the english and german entries correctly.

**Comment by aplaice** [comment]
Oops! You're right! Thanks for catching this!

**Comment by ohare93** [comment]
Could be time to convert the csvs to tsvs, which would limit the amount of delimiting required throughout all files :sweat_smile:

**Comment by aplaice** [comment]
In this case I don't think we needed to quote the fields at all, though (none of the fields (should have) contained commas, so none of them needed to be quoted).

However, not having to quote any fields, ever (which would be the case with TSVs) would make things much easier — I didn't realise that the quotes were actually unnecessary until now...

Alternatively/in addition, we could have a "number of columns" check.
