### ISSUE TITLE
The v5.0 SV and SV_EXTENDED releases can't be imported

### ISSUE THREAD

**Issue by JohanSpaedtke** [anki-geo/ultimate-geography#480]
Trying to import v5.0 SV or v5.0 SV_EXTENDED results in the following error

> Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-29 16:59:54
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩
Caught exception:
Traceback (most recent call last):
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 114, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 103, in import_deck_from_path
    if importer.load_deck(directory_path):
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 41, in load_deck
    deck.save_to_collection(self.collection, import_config=import_config)
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/representation/deck.py", line 131, in save_to_collection
    self.save_decks_and_notes(collection=collection,
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/representation/deck.py", line 154, in save_decks_and_notes
    note.save_to_collection(collection, self, model_map_cache, import_config=import_config)
  File "/Users/johan/Library/Application Support/Anki2/addons21/1788670778/representation/note.py", line 122, in save_to_collection
    collection.add_note(self.anki_object, deck.anki_dict["id"])
  File "anki/collection.py", line 373, in add_note
  File "anki/notes.py", line 68, in _to_backend_note
TypeError: None has type NoneType, but expected one of: bytes, unicode

Some cards are successfully imported (167 for SV and 250 for SV_EXTENDEND)

Russia seems to be one of the cards/notes not imported and the entry in both JSONs look like this

        {
            "__type__": "Note",
            "data": "",
            "fields": [
                "Ryssland",
                "",
                "Moskva",
                "",
                "",
                "<img src=\"ug-flag-russia.svg\" />",
                null,
                "<img src=\"ug-map-russia.png\" />"
            ],
            "flags": 0,
            "guid": "u3u7Z|VQV`",
            "note_model_uuid": "0a39f994-daaf-11e8-b984-a0481cc15658",
            "tags": [
                "UG::Europe",
                "UG::Sovereign_State"
            ]
        }

and given that the EN version doesn't have a `null` there and that's the only `null` among the notes in the Swedish ones I guess that it might be the culprit? It's a bit weird also that the English one below has both English and German text in that particular field. 
 
       {
            "__type__": "Note",
            "data": "",
            "fields": [
                "Russia",
                "",
                "Moscow",
                "",
                "",
                "<img src=\"ug-flag-russia.svg\" />",
                "Slovakia (with coat of arms),Slowakei (mit Wappen)",
                "<img src=\"ug-map-russia.png\" />"
            ],
            "flags": 0,
            "guid": "vf)G?[_?Pf",
            "note_model_uuid": "43e2586a-9a65-11e8-a777-a0481cc15658",
            "tags": [
                "UG::Europe",
                "UG::Sovereign_State"
            ]
        },

**Comment by axelboc** [comment]
Probably linked to this https://github.com/anki-geo/ultimate-geography/pull/478/files -- I'll update the ZIP files in the release notes.

**Comment by axelboc** [comment]
Done, let me know if the new ZIP works.

**Comment by JohanSpaedtke** [comment]
Both ZIP files works perfectly now. Thnx
