### ISSUE TITLE
Some mistakes in the map of China

### ISSUE THREAD

**Issue by ruin1990** [anki-geo/ultimate-geography#494]
I found some mistakes in the map of China. Among them, Taiwan (which should be uncontested and belongs to China. Both Taiwan and other Chinese believe that there is only one China) and the islands in the South China Sea are not marked or even wrong, which makes me very sad, because the wrong map here can not be popularized. I don't know what method can solve this problem

**Comment by ohare93** [comment]
This deck takes a neutral stance of "if it could be contested, then we will talk about it as if it is contested". Taiwan very much is contested on the political stage.

Replying to your opinion about which countries are truly countries with my own opinion: the Taiwanese do not believe this.

**Comment by ukanuk** [comment]
My impression for this deck has been "let Wikipedia handle the controversies". The English Wikipedia map does mark Taiwan and some other areas, but in different colors. 

A map with multiple colors imo gives too many hints for the Map>Country cards, but we could show a simplified map on the card front and a full map version with explanation on the card back. Similar to how flag images are sometimes modified on the card front to blur text, but full version is shown on reverse.

**Comment by aplaice** [comment]
> My impression for this deck has been "let Wikipedia handle the controversies".

Yes, exactly. (We follow Wikipedia since they've likely already had the relevant discussions on these topics, and are besides better equipped to handle such issues.)

The map that we're using is [here](https://commons.wikimedia.org/wiki/File:China_in_its_region_(claimed_and_disputed_hatched).svg).

<hr/>

I don't think that having a debate on the topic here would be worthwhile, so I'm closing. 

If you open a discussion on Wikipedia and change the consensus (and maps) there, then we'll follow suit.

**Comment by ukanuk** [comment]
> The map that we're using is [here](https://commons.wikimedia.org/wiki/File:China_in_its_region_(claimed_and_disputed_hatched).svg).

To clarify slightly more, per [CONTRIBUTING.md](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#map-field) , all maps in this deck come from the [SVG locator maps](https://commons.wikimedia.org/wiki/Category:SVG_locator_maps_of_countries_(16:9_regional_location_map_scheme)) project on Wikimedia.

That way all the maps have a uniform style.

>... Open a discussion on Wikipedia and change the consensus (and maps) there... 

So, any updated consensus/maps should be specifically within the SVG Locator Maps project, not from Wikipedia's main country article as I initially assumed.

**Comment by aplaice** [comment]
> So, any updated consensus/maps should be specifically within the SVG Locator Maps project, not from Wikipedia's main country article as I initially assumed.

If the Wikipedia main country article were substantially changed, we'd also likely follow suit, probably first by asking for/about the relevant changes in the Locator Maps project.
