### ISSUE TITLE
Where is the English version for extended decks

### ISSUE THREAD

**Issue by ruin1990** [anki-geo/ultimate-geography#495]
I cannot find it in ankiweb or github

**Comment by aplaice** [comment]
The same fields (in `src/data/*.csv`) are used to generate both the standard and the extended deck. (In the standard deck, the 8 fields per note are used to create 4 cards per note (Country→Capital, Capital→Country, Map→Country, Flag→Country).  In the extended deck, the same 8 fields per note are used to create 6 cards per note (the same 4 as previously and also Country→Flag and Country→Map).

AnkiWeb doesn't have the extended deck.

The extended deck (as a CrowdAnki deck) is available here:

https://github.com/anki-geo/ultimate-geography/releases/tag/v5.0

as Ultimate_Geography_v5.0_EN_EXTENDED.zip  .

**Comment by ruin1990** [comment]
Oh, Thanks a lot for you help, I find it.  : )
