### ISSUE TITLE
Upgrade to latest BrainBrew

### ISSUE THREAD

**Issue by aplaice** [anki-geo/ultimate-geography#502]
This should hopefully be straightforward, if not completely trivial. (See #498 for potential errors.)

It might be useful, so that potential fixes (like for encoding issues) can be easily propagated to us as well.

<hr/>

I'll have a look soon-ish. I'm opening an issue to keep track and in case anybody has any comments.

**Comment by ohare93** [comment]
Let me get a few small fixes released, then I'll do this upgrade myself :+1: You're right, it's a very minor change anyways

**Comment by ohare93** [comment]
Some optional changes that would be good to do with the latest versions of Brain Brew:
1. Change from csvs to tsvs :+1: 
2. Separate out the Note Model data into it's own yaml source files
