### ISSUE TITLE
Translating the description to Spanish

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#510]
Hi,

I've seen in the Chinese translation that the description was also translated. What should I do to translate it to Spanish? It's just about creating `desc_es.html`? (pinging @ohare93 as the Brain-Brew maintainer. ^^)

**Comment by ohare93** [comment]
I am summoned.

**Comment by josealberto4444** [comment]
So, do I have to do anything more? Like changing a script or something, I don't know. =P

**Comment by ohare93** [comment]
See my comment here https://github.com/anki-geo/ultimate-geography/issues/504#issuecomment-1005408179 👍 

You can see @ruin1990 made these suggested changes in the Files Chanaged of his Chinese Language PR https://github.com/anki-geo/ultimate-geography/pull/499/files 👍

**Comment by ohare93** [comment]
Feel free and just provide the translated deck description, if you wish 👍 one of us will make the required changes to the Recipe files 😁

**Comment by josealberto4444** [comment]
Oops, we posted at the same time. I'll make the changes. ^^

However, I have a doubt. Will this change (only to the description file) affect the note type or have any disadvantage as this one

> The issue here is just that it will remove all reusability in the recipe tasks

? I don't fully understand the implications of this.

I'm not trying to translate the fields, but only the description. =)

**Comment by aplaice** [comment]
> The issue here is just that it will remove all reusability in the recipe tasks

AFAIU this would only be the case if the templates (the immutable text such as "Capital", "flag similar to" etc.) were translated, and just translating the deck description file does not significantly increase the complexity of the YAML recipe.

The note type will stay the same. (The deck description is part of the deck itself (as in "the abstract deck object" as opposed to "the deck, the collection of the notes/cards"). The note type is orthogonal to the deck.)

**Comment by ruin1990** [comment]
Note that desc_xx.html must be encoded in UTF-8.
Otherwise, collaborators in other countries may not be able to compile successfully
I write a [Guide](https://github.com/anki-geo/ultimate-geography/discussions/503) may be help for you.
