### ISSUE TITLE
Link to additional information

### ISSUE THREAD

**Issue by DataStrategist** [anki-geo/ultimate-geography#532]
Thanks for a great deck!

I thought it could be a useful feature to add a link to the Wikipedia page for each entity to help contextualize completely new information that users might be struggling with. This link could be available in all the answer views. Hope that's a helpful suggestion!

**Comment by DataStrategist** [comment]
Thanks for that. Are there any guides to show where to edit the card templates? I'm synching from AnkiWeb, but it seems the instructions on the `README` are for a different deck acquisition strategy?

**Comment by ukanuk** [comment]
You'll need to use the regular Anki desktop software to edit your cards, from https://apps.ankiweb.net. You can find a lot of helpful YouTube tutorials on making and editing cards with Anki, and there is also good official documentation at https://docs.ankiweb.net/getting-started.html

**Comment by aplaice** [comment]
The way you acquired the deck doesn't really change much wrt editing the card templates.

In desktop Anki, you can, (among other ways), edit the template for a card/note, by (when you're reviewing a card of a given type) pressing the keyboard shortcut <kbd>e</kbd> and then <kbd>Ctrl</kbd><kbd>l</kbd>. 

As @ukanuk mentioned, you can see more in the [official docs](https://docs.ankiweb.net/templates/intro.html).

I _think_ it's also possible to edit the template on AnkiDroid and AnkiMobile.

<hr/>

One disadvantage of editing the note templates by yourself (that I forgot to mention) is that when you update the deck (via CrowdAnki or via re-downloading the shared deck from AnkiWeb (i.e. not just syncing your collection)), your changes to the templates will be overwritten and you'll have to redo them.  AUG isn't updated that frequently, though (and you don't have to update for each release), so it's hopefully not too annoying.

**Comment by DataStrategist** [comment]
Thanks for this... works great!  

My addition: 1 minute videos! `<a href="https://www.youtube.com/results?search_query={{Country}}+in+one+minute">1 min</a>`.

A pic is worth a thousand words!
