### ISSUE TITLE
Use vector flags for all available countries

### ISSUE THREAD

**Issue by flipflop97** [anki-geo/ultimate-geography#534]
While this deck uses mostly svg images for flags of countries, some flags use raster images while they are freely available as svg like [Croatia](https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg). Is there any reasoning behind this? Otherwise, it would be nice to replace the raster images with vector images.

**Comment by axelboc** [comment]
It's a [matter of file size](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#flag-field). The cut off is currently at 50 kB for SVGs; anything greater is converted to PNG. Given that there are only 18 PNG flags left, that flags weigh 11 times less than maps all up (1 MB vs 11 MB), and that that phones have more storage these days. it might be worth reconsidering whether this limit still makes sense.

**Comment by KentGrigo** [comment]
I've made a PR for this issue here: https://github.com/anki-geo/ultimate-geography/pull/577

It doesn't vectorize all the flags as I was uncertain about how to handle some flags due to https://github.com/anki-geo/ultimate-geography/issues/111.
I've added further details in a comment to the PR.

**Comment by KentGrigo** [comment]
Note: As @axelboc has already mentioned, this will increase the size of the files above the 50 kB.
But in case you want to abandon this constraint, https://github.com/anki-geo/ultimate-geography/pull/577 is a partial solution.

**Comment by aplaice** [comment]
The following flags still need to be vectorized:
[ ] Belize
[ ] Bolivia
[ ] Costa Rica
[ ] El Salvador
[ ] Peru
[ ] Venezuela

These flags were not vectorized because they also needed to be blurred:
- Bolivia
- El Salvador

and these flags because they didn't correspond to the first flag on Wikipedia,
- Belize
- Bolivia
- Costa Rica
- Peru
- Venezuela

(Copied from @KentGrigo's summary. (Thanks!))

**Comment by KentGrigo** [comment]
Sorry for going AWOL. A lot of personal things came up.
I've now vectorized the rest of the flags, except the blurred versions, which are still rasterized. 
PR is here: https://github.com/anki-geo/ultimate-geography/pull/587
