### ISSUE TITLE
Accidentially  delteted cards one year ago. Can't restore

### ISSUE THREAD

**Issue by mmfs37** [anki-geo/ultimate-geography#540]
I imported the deck about one year ago. I finished it today (yeah long time I know I stopped anki for about 8-9 months due to being stupid)
While importing I deleted cards I did not wanted to study directly so mostly territories etc.
I can't get them back. If I go to browse cards they are still entered as deleted. If I import the new cards of v5 got added but those deleted stay deleted. How do I get those cards back. I want to learn them now

**Comment by aplaice** [comment]
> If I go to browse cards they are still entered as deleted.

Do you mean that they're absent or still explicitly marked as deleted? (If the latter, which version of Anki are you using now (and which version had you been using — if you remember — when you deleted the cards?)?)

> so mostly territories etc.

We've removed a couple of small dependent territories from the deck outright, so they might just not be present in the deck any longer. If you remember which territories they were I could check whether that's the case (and how best you could obtain them (we have a legacy deck, somewhere, that contains some of the removed notes)).

(I've just tested (with 2.1.40) deleting cards and reimporting and the deleted cards are recreated when reimporting.)

**Comment by ohare93** [comment]
"They are still there but marked as deleted."

What does this mean?

I am getting some 'AnkiApp' vibes here... Just to confirm: you are using [Anki](https://apps.ankiweb.net/) and not [AnkiApp](https://www.ankiapp.com/), right? Many people have been tricked in the past, and it leads to these communication issues. Though I hope I am wrong :disappointed:

**Comment by mmfs37** [comment]
> "They are still there but marked as deleted."
> 
> What does this mean?

Sorry if my anki looks kind of different. I use a lot of plugings. 
![image](https://user-images.githubusercontent.com/100991030/170779525-83acb7c0-3403-4a71-b01f-8d5eeba55457.png)
As you can see all of those cards (upper half) in the deck are deleted.
I can't press then or anyhting


> I am getting some 'AnkiApp' vibes here... Just to confirm: you are using [Anki](https://apps.ankiweb.net/) and not [AnkiApp](https://www.ankiapp.com/), right? Many people have been tricked in the past, and it leads to these communication issues. Though I hope I am wrong 😞

No like I said I mainly use the anki -windows app with the 2.1.49 version. 
On mobile I would use the official ipad app or ankidroid. But windows app is about 90% the one used

**Comment by ohare93** [comment]
Are you using any add-ons? Does the same happen if you disable them? Simply [hold shift while starting anki to disable them all temporarily](https://docs.ankiweb.net/files.html?highlight=hold%20shift#startup-options) :+1:

**Comment by aplaice** [comment]
> I do not know which got deleted exactly. I have seen for example on the github that picture of the christmas islands. I do not have those. I have counted the deleted ones and it shows that 28 cards are deleted.

After some investigation — you might be able to check in the Anki profile folder, in `deleted.txt` (`User 1/deleted.txt`).

>  As you can see all of those cards (upper half) in the deck are deleted. I can't press then or anyhting

That's very weird and quite interesting — when I delete notes they're displayed in the Anki card browser as deleted but only until I close the browser (not even Anki itself) and reopen it.

Perhaps "checking your database" (Tools > Check database) might help? (If this has weird effects (it definitely _should not_) you can restore from a backup or by forcing a full sync from AnkiWeb.)

> How did you reimport? I tried with pressing anki's "import file" and pressing the file that was downloaded from the official anki get shared page (https://ankiweb.net/shared/info/2109889812)

I had tested with CrowdAnki — I'll see if reimporting the APKG has the same effect.

**Comment by aplaice** [comment]
I hope that you've solved your issue! (If not and you need further advice, please comment!)
