### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by giovanni-cutri** [anki-geo/ultimate-geography#554]
Hello, first of all thanks for this awesome deck!
I have noticed that an Italian translation is not available yet, I am starting to work on it right now.

**Comment by axelboc** [comment]
Awesome to hear, thanks! The [CONTRIBUTING](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md) guide should give you some pointers, but don't hesitate to let us know if you need any help. Good luck!
