### ISSUE TITLE
Flag Images

### ISSUE THREAD

**Issue by bgub** [anki-geo/ultimate-geography#556]
The flag images don't display for me in AnkiWeb... is there a way to fix that?

**Comment by aplaice** [comment]
Are the map images displayed?  It's rather hard to debug without more information. (I just checked and for me, the flag images are displayed on the AnkiWeb web interface.)

**Comment by bgub** [comment]
Sorry, it looks like I downloaded it incorrectly or there was some other issue on my end -- other decks had the same issue. I was able to fix the problem by deleting and redownloading with a different computer. Thanks!
