### ISSUE TITLE
Free AnkiHub account

### ISSUE THREAD

**Issue by AnKingMed** [anki-geo/ultimate-geography#568]
As this is a very popular community deck, I would be willing to give you a free lifetime AnkiHub account if you would like to upload it there for easier collaboration.  You can still share the deck elsewhere as well. www.ankihub.net

Feel free to email me with any questions or to get set up. ankingmed@gmail.com

**Comment by axelboc** [comment]
Hi @AnKingMed, thanks a lot for the offer! Looks like a powerful product.

However, git (+ GitHub), BrainBrew and CrowdAnki have done us very well so far, in my opinion. The number of translations and people opening PRs to fix typos and such is proof that the current stack does foster collaboration. Sure, there's plenty of room for improvement, but I don't think migrating to another stack would be worth it and wise at this point, especially one that isn't fully open source and not "portable" (i.e. the use of git means we're not dependent on GitHub).
