### ISSUE TITLE
Missing capitals for territories

### ISSUE THREAD

**Issue by KentGrigo** [anki-geo/ultimate-geography#590]
I noticed that some territories are missing info about the capitals.

To find the missing territories (and a bit more), I searched for `Capital:"" -tag:*Oceans*`.
Here's what (I hope) is a complete list of the mappings.

Sicily - Palermo
Mayonette - Mamoudzou
Réunion - Saint-Denis
Falkland Islands - Stanley
Saint Martin - Philipsburg
Akrotiri and Dhekelia - Episkopi Cantonment
Alaska - Juneau
Cayman Islands - George Town
Sint Maarten - Philipsburg
British Virgin Islands - Road Town
Anguilla - The Valley
Bermuda - Hamilton
Guernsey - St. Peter Port
Sardinia - Cagliari
Martinique - Fort-de-France
Corsica - Ajaccio
French Guiana - Cayenne
Bali - Denpasar
Turks and Caicos Islands - Cockburn Town
Guadeloupe - Basse-Terre
Jersey - St Helier
Madeira - Funchal
Isle of Man - Douglas
Gibraltar - Westside
Azores - Ponta Delgada (executive), Angra do Heroísmo (judicial), Horta (legislative)
Zanzibar - Zanzibar City
Canary Islands - Las Palmas & Santa Cruz de Tenerife
Wallis and Futuna - Mata Utu
Hawaii - Honolulu
Bougainville - Buka
Northern Mariana Islands - Saipan
American Samoa - Pago Pago

**Comment by aplaice** [comment]
Thanks for looking into this.

However, these were deliberately removed (or for the couple new cases deliberately not added), according to [the inclusion rules for territories/islands that aren't sovereign states](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#political-geography).  The various threads discussing the issue which ended up settling on the described policy are linked in the above-mentioned section of CONTRIBUTING.md.  In _very_ brief: some small "territories" (catch all of all the non-sovereign states categories) are of some interest (people might want to know where/what they are), but not great interest (having capitals/flags would overload/bore most learners).

Obviously, feel free to comment here or in the relevant threads if you disagree with these decisions.

**Comment by KentGrigo** [comment]
Ah! I figured there was a reason why there was so many territories without a capital, but I checked the Content Guidelines parts of CONTRIBUTING.md and didn't find any mentions of exclusion.

Sorry for having bothered you with this.

**Comment by ohare93** [comment]
If you'd like to have these capitals you can always use an old version of the deck :+1: I haven't upgraded for a while, in the vain hopes of making some type of optional deck extension that would reinclude these before I do :sweat_smile:

**Comment by KentGrigo** [comment]
Would it make sense to add the capital information along with the population and area size and then filter based on those when generating the cards? 
It'll take some work to fetch all the data, but then users can make cards for all the capitals if they want to. The same goes for the population and area size.
