### ISSUE TITLE
"The front of this card is blank" on some cards after updating

### ISSUE THREAD

**Issue by agos** [anki-geo/ultimate-geography#594]
Hello and thanks for your work on the project. I've learned a lot through it and I love it ❤️ 

This week I have upgraded from the apkg format to v5.1 and it went smoothly, other than a few cards coming up during review as "The front of this card is blank" with no further info.

The cards involved are (at least) Northern Mariana Islands, Guernsey, Cayman Islands.

I'm a bit lost as to what happened, and how it can be fixed. I understand people updating from apkg is going to be increasingly rare, but it might be worth a mention in the upgrade instructions.

**Comment by axelboc** [comment]
Hi @agos, it means those cards have been removed from the deck (mostly the `flag -> country` cards of a few very small islands and dependent territories). The fix is to click on _Tools_ > _Empty cards..._. Anki will remove all empty cards automatically.

Looks like the instructions on [upgrading after an APKG install](https://github.com/anki-geo/ultimate-geography#first-upgrade-after-apkg-import) in the README do not mention clicking on _Empty cards_. Do you remember which version of the deck you installed initially?

**Comment by agos** [comment]
hi @axelboc, thanks for the help! They are indeed all small islands and territories.

By triangulating release notes and the creation date of my AnkiWeb account I'm fairly confident that I had version 3.3 installed prior to this upgrade.

Do you think it might be worth it to mention in the README that this can happen? I'd be happy to contribute a PR myself

**Comment by axelboc** [comment]
> Do you think it might be worth it to mention in the README that this can happen? I'd be happy to contribute a PR myself

Definitely worth mentioning in the `README`, and thanks for the offer! I might just ping @aplaice to see what he thinks -- it'd be good to avoid duplicating information already present on the [wiki page](https://github.com/anki-geo/ultimate-geography/wiki/Upgrade-instructions), but I'm not 100% sure how the information on this page correlates with upgrading from an APKG installation and the instructions for this use case provided in the README.

**Comment by aplaice** [comment]
Firstly, sorry @agos that this hasn't been described in the "First upgrade after APKG import" instructions!

<hr/>

> it'd be good to avoid duplicating information already present on the [wiki page](https://github.com/anki-geo/ultimate-geography/wiki/Upgrade-instructions),

The relevant information is linked from the Wiki:

> Some notes and cards were removed to reduce bloat. For details, please see the [v4.0 release](https://github.com/anki-geo/ultimate-geography/releases/tag/v4.0). The upgrade process is also described there, in detail.

and is actually present here:

https://github.com/anki-geo/ultimate-geography/releases/tag/v4.0

(Aside: should we just copy the appropriate part of the v4.0 release notes into the Wiki page, for consistency?)

Unfortunately, the Wiki page is not clear on which parts apply to upgrades from an APKG import, and AFAICT only the ["From v3.3."](https://github.com/anki-geo/ultimate-geography/wiki/Upgrade-instructions#from-v33) instructions are applicable.

I _think_ that it might be easiest to just add a sentence to the ["First upgrade after APKG import"](https://github.com/anki-geo/ultimate-geography/blob/master/README.md#first-upgrade-after-apkg-import) section in the Readme, saying that if you're upgrading from v3.3 (to whatever version), then the "How to upgrade" part of the [v4.0 release notes](https://github.com/anki-geo/ultimate-geography/releases/tag/v4.0) applies? (The alternative would be to add a section on "From APKG" upgrades to the Wiki page, but that would mean "APKG upgraders" might be confused by all the other irrelevant information, and the Wiki page would become even more complex.)
