### ISSUE TITLE
[SV] Formal name for United Kingdom

### ISSUE THREAD

**Issue by melissis** [anki-geo/ultimate-geography#600]
In 2016 or so, the offical Swedish name for United Kingdom was rather quietly changed from "Storbritannien" to "Förenade konungariket Storbritannien och Nordirland", with "Förenade kungariket" as a short form. This is a more literal translation of the name in the original language, while the former translates to "Big Britain". Using the new name probably sparks confusion in most people, but the authorities use it.

I'm not sure if it should be added to country info, and if so, how it should be written. This is the introduction on Swedish language Wikipedia:

> **Storbritannien**, formellt *Förenade konungariket Storbritannien och Nordirland* med kortform *Förenade kungariket* [...]

E.g.:

> **Storbritannien**, formally *Förenade konungariket Storbritannien och Nordirland* with short form *Förenade kungariket* [...]

**Comment by axelboc** [comment]
Hi @melissis, thanks for the heads' up! However, as per our [guidenlines](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#country-field), we take country names from the titles of the Wikipedia articles. In this case, the title is still [Storbritannien](https://sv.wikipedia.org/wiki/Storbritannien). There's a [discussion thread(https://sv.wikipedia.org/wiki/Diskussion:Storbritannien) about changing it, but it doesn't seem to be going ahead for now. FYI, Wikipedia's guidelines dictate that a country name has to become mainstream before it can be used as the title of the country's article.

That being said, please feel free to mention _Förenade kungariket_ in the _Country info_ field! Either "Also know as" or "Formally known as" would work I think, but up to you.

**Comment by melissis** [comment]
> However, as per our [guidenlines](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md?rgh-link-date=2023-04-16T16%3A34%3A38Z#country-field), we take country names from the titles of the Wikipedia articles. In this case, the title is still [Storbritannien](https://sv.wikipedia.org/wiki/Storbritannien). There's a [discussion thread](https://sv.wikipedia.org/wiki/Diskussion:Storbritannien) about changing it, but it doesn't seem to be going ahead for now. FYI, Wikipedia's guidelines dictate that a country name has to become mainstream before it can be used as the title of the country's article.

That being said, please feel free to mention Förenade kungariket in the Country info field! Either "Also know as" or "Formally known as" would work I think, but up to you.

I should have been a bit clearer, perhaps. I was only thinking about the Country info field.

Some of the Swedish columns have "Formally", but I don't know I should put the long name there, or the short name, or both.

**Comment by axelboc** [comment]
Oh my bad! I think just the short name is enough, then, don't you think?

**Comment by horwitz** [comment]
@melissis are the other Swedish examples (at least mostly) using long names?

**Comment by melissis** [comment]
> @melissis are the other Swedish examples (at least mostly) using long names?

@horwitz you mean if other cards also include the full formal names? I guess not. For example, Sweden is just "Sverige", even though the formal name is "Konungariket Sverige" (Kingdom of Sweden). But the thing with United Kingdom is that the short form formal Swedish name is completely different from the Wikipedia common name ("Förenade kungariket" vs. "Storbritanien").

**Comment by horwitz** [comment]
I was thinking that the deck should at least be consistent... if there aren't other examples, then maybe this issue isn't so relevant? or, if deemed a change that should be made, perhaps this change would belong to one of broader scope (i.e., affecting more countries)? (and, thus, perhaps not for v5.2)

**Comment by aplaice** [comment]
I suspect that there aren't many other cases, here, similar to the UK, so I don't think this needs to be part of some broader re-evaluation.

There's Kongo-Kinshasa (formally "Demokratiska republiken Kongo"), Kongo-Brazzaville (formally "Republiken Kongo"), but here the formal names are short.

The most similar might be the USA:

```
Formellt Amerikas förenta stater, även känt som Förenta staterna.
```

(Swedish Wikipedia just uses "USA" for the article title.)

so there's some argument for including both short and long (with the same structure as for the USA), but I'd go with just "Formellt Förenade kungariket.". (Whatever sounds most natural!)

**Comment by horwitz** [comment]
has it been resolved what (if any) changes actually should be made here? (it sounds like the issue is whether or not to update the SV "Country info" field for the UK(?))

**Comment by axelboc** [comment]
Just need to add "Formellt Förenade kungariket." to the SV _Country info_ field, if you're up for it @horwitz
