### ISSUE TITLE
Kazakhstan Capital Name Changed Back to Astana

### ISSUE THREAD

**Issue by ehynnek** [anki-geo/ultimate-geography#608]
In 2022, the Kazakhstan government changed the name of the capital city, Astana, back from Nur-Sultan, which was the name it had from 2019-2022. Thus, the current card for Kazahstan is outdated.

Source: https://www.reuters.com/world/asia-pacific/kazakh-capital-renamed-again-ex-leaders-legacy-fades-2022-09-16/

**Comment by aplaice** [comment]
Thanks for bringing this up! Yes, that is the case! (It's been fixed in master, but not released, yet:

https://github.com/anki-geo/ultimate-geography/blob/master/src/data/capital.csv#L57

)
