### ISSUE TITLE
Incorrect capital name for Kazakhstan

### ISSUE THREAD

**Issue by maurostorti** [anki-geo/ultimate-geography#618]
The name of the capital of Kazakhstan was reverted to Astana in September 2022 and is no longer called Nur-Sultan.

Source: https://en.wikipedia.org/wiki/Astana#Names

**Comment by aplaice** [comment]
Thanks for noticing! This has been already fixed in the "source" (`master`) (in #571), but not yet released! (v5.2 is coming out soon!)
