### ISSUE TITLE
Generating maps

### ISSUE THREAD

**Issue by valkmj** [anki-geo/ultimate-geography#622]
Hey, thanks for this deck, it is amazing! I would like to add some custom cards, how did you create the maps of each country? Thanks in advance

**Comment by aplaice** [comment]
Hi!

[This discussion](https://github.com/anki-geo/ultimate-geography/discussions/615#discussioncomment-7957192) should hopefully answer your question.

(In brief: most of the country maps come from Wikimedia (not made by us); the sea maps and some of the country maps were created by us (though also uploaded to Wikimedia, for ease of reuse by other people). (See [sources.csv](https://github.com/anki-geo/ultimate-geography/blob/master/sources.csv) for location on Wikimedia.) The process we used is outlined in the discussion above.)

If you have any questions feel free to ask, here or in the other thread!

**Comment by valkmj** [comment]
Thanks! Your work is appreciated :)
