### ISSUE TITLE
Update Kyrgyzstan’s flag

### ISSUE THREAD

**Issue by rlanday** [anki-geo/ultimate-geography#625]
See:
https://twitter.com/EmpTigerstar/status/1758184506169671715
> I learned that Kyrgyzstan at the end of 2023 changed their flag slightly because apparently they didn’t want their sun to be “confused with a sunflower” so they made it spiky.

and
https://www.reuters.com/world/asia-pacific/kyrgyzstan-moves-rid-national-flag-likeness-fickle-sunflower-2023-11-29/
> BISHKEK, Nov 29 (Reuters) - Kyrgyzstan's parliament voted on Wednesday to tweak the design of the national flag after critics, including President Sadyr Japarov, said its central element looked like a sunflower which in the local culture symbolises fickleness and servility.

Wikipedia uses the new flag:
https://en.wikipedia.org/wiki/Kyrgyzstan#/media/File:Flag_of_Kyrgyzstan.svg

**Comment by aplaice** [comment]
Thanks for raising this! :)
