### ISSUE TITLE
South Ossetia is part of Europe?

### ISSUE THREAD

**Issue by Brian141421** [anki-geo/ultimate-geography#632]
Hi, 

I noted that South Ossetia has the tag UG::Asia, but not the tag UG::Europe. This is odd, since all the surrounding countries do have the tag UG::Europe, viz., Russia, Georgia, Armenia, Azerbaijan, Armenia. 

My proposal is to change main.cvs, and to change UG::Asia to UG::Europe for South Ossetia

**Comment by aplaice** [comment]
Thanks for bringing this up!

I agree that given that all the surrounding countries have the Europe tag, so should South Ossetia. (At least for now.)

In the longer term we _might_ (or not) want to make all the Caucasus countries have, say, both Europe and Asia tags. (Tags aren't really very user-facing (they're not something the user directly learns), so the usual argument about strongly avoiding back-and-forth doesn't hold as much.)

We _might_ also want to add a section about tags to CONTRIBUTING.md, in the longer term. (All the various tag decisions are currently split among many issues.)
