### ISSUE TITLE
Getting 'The front of this card is blank' on clean install

### ISSUE THREAD

**Issue by dusky-seaside-sparrow** [anki-geo/ultimate-geography#643]
I installed `Ultimate_Geography_v5.2_NL.zip` using CrowdAnki following the [instructions in the README](https://github.com/anki-geo/ultimate-geography?tab=readme-ov-file#getting-started). However, already the second card in my review of the deck says "The front of this card is blank". The back of the card is also blank.

It is the card with two fields:

- Country: "Noord-Amerika" (North America)
- Map: image of map with the North American continent highlighted

I fixed this by using the option 'Empty Cards...' from the 'Tools' menu, which deleted 100 cards (I had to uncheck the 'Keep notes with no valid cards') Is this a bug in the release, or did I miss a step in the instructions?

**Comment by aplaice** [comment]
Thanks for reporting!

Unfortunately, I can't reproduce the issue with a fresh Anki profile. I also can't think of how missing a step in the instructions would result in this particular problem.

Which version of Anki are you using? Had you been using another language version of AUG previously?

**Comment by dusky-seaside-sparrow** [comment]
Anki v24.06.3 on macOS. This is my first time installing the Ultimate Geography Deck.

**Comment by dusky-seaside-sparrow** [comment]
I also tried to reproduce this with a new profile, but now I don't get any empty cards on review. Also when using 'Empty Cards...' from the Tools menu it says there are no empty cards.

So it was probably a one-time fluke, I'll close the issue.

**Comment by aplaice** [comment]
Thanks for checking! If you experience this again, please do comment — one-time flukes are still annoying and we'd like them eliminated!
