### ISSUE TITLE
missing flags

### ISSUE THREAD

**Issue by Oligodendrocytes** [anki-geo/ultimate-geography#661]
i noticed there are some missing flags (mostly islands i think) for example the US virgin islands flag is existing while british virgin islands isnt 

is there a reason for that?

**Comment by axelboc** [comment]
The [content inclusion rules](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#content-inclusion-rules) in the CONTRIBUTING guide should answer your question. See also https://github.com/anki-geo/ultimate-geography/issues/640#issuecomment-2253285197 for alternatives. :blush:
